version: '3'

services:
  node:
    image: velas-sphere-node-local
    command: "node"
    ports:
      - "3000:3000" # api
      - "8081:8081" # provider
    volumes:
      - ./db:/db

  plugin:
    image: velas-sphere-plugin-local
    command: "plugin"