version: '3'

services:
  requester:
    image: velas-sphere-requester-local
    command: "requester"
    networks:
      - frontend

  provider:
    image: velas-sphere-provider-local
    ports:
      - "8081:8081"
    command: "provider"
    networks:
      - primary
      - frontend

  plugin:
    image: velas-sphere-plugin-local
    command: "plugin"
    networks:
      - primary

networks:
  primary:
  frontend: